import Box from '@mui/material/Box';
import Grid from '@mui/material/Unstable_Grid2';
import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';

import Summary from '@components/Summary';
import { withAuthSsr } from '@lib/AuthSession';
import { useGetSummaryQuery } from '@redux/Summary';

const Home: NextPage = () => {
  const { data: summaryData } = useGetSummaryQuery(undefined, { pollingInterval: 2 * 1000 });

  return (
    <Box sx={{ flexGrow: 1 }}>
      <Head>
        <title>Pi-hole dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Grid container spacing={2}>
        <Grid xs={12}>
          <Summary data={summaryData} />
        </Grid>
      </Grid>
    </Box>
  );
};

// use wrapping function to check if user is authenticated.
// if the user is NOT authenticated, redirect to the login page
// obtained from https://stackoverflow.com/a/70737180/3053548
export const getServerSideProps: GetServerSideProps = withAuthSsr(() => {
  return {
    props: {},
  };
});

export default Home;
