name: Dependabot automerge
on: pull_request
# description: Automerge dependabot pull requests

jobs:
  automerge-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      # actions: write
      # issues: write
    if: |
      startsWith(github.event.pull_request.title, 'build(deps):') ||
      startsWith(github.event.pull_request.title, 'build(devDep):')
    steps:
      # - uses: fastify/github-action-merge-dependabot@v3.0.0
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}

      # - name: '@dependabot squash and merge'
      #   uses: actions/github-script@v2
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     script: |
      #       await github.issues.createComment({
      #         owner: "${{ github.repository_owner }}",
      #         repo: context.payload.repository.name,
      #         issue_number: context.payload.pull_request.number,
      #         body: '@dependabot squash and merge'
      #       })
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Enable auto-merge for Dependabot PRs
        # if: ${{contains(steps.metadata.outputs.dependency-names, 'my-dependency') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
